modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="decore"
version="1.0.1"
displayName="DECore"
credits="Thanks to my kids for wanting more from their games."
displayURL="https://www.lededesigns.com/decore"
authors="Leland Ede (zaxis701)"

[[dependencies.decore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.decore]]
    modId="appliedenergistics2"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


